### PR TITLE
interrupt suspension functions

### PR DESCRIPTION
**Pull request by recallmenot**
добрые друзья,

I'd like to propose some basic interrupt suspension functions.
The intention is to temporarily disable all interrupts except the one you're interested in so it can run un-impeded and with as little delay as possible, without the need for nesting.
I hope this will be useful and is light enough to be part of ch32v003fun.

### CODE REVIEW

**Comment by cnlohr** [comment]
Makes sense.

Have you tested this significantly?

**Comment by recallmenot** [comment]
Not what I'd call extensively, though I have noticed an improvement in timing jitter over elevating IRQ priority (afaik) and it's currently the best I can do.

**Comment by cnlohr** [comment]
I care more about correctness and convenience.  So if you think it's correct, I'll accept it.

**Comment by recallmenot** [comment]
to the best of my knowledge, it should be.
It's not like I have hundreds of usecases to test it either...
it worked for me, I can only hope it works for everyone else too.

**Comment by cnlohr** [comment]
Excellent!

**Pull request merged**
