### PR TITLE
Adding example remapping TIM2's output

### PR DESCRIPTION
**Pull request by prosper00**
Any interest in adding this example to your repo, demonstrating the use of the AFIO feature?

### CODE REVIEW

**Comment by cnlohr** [comment]
Please switch to using printf over debug pins.  It works with all programmers now.

As far as wanting this examples, YES! I would love it.

**Comment by prosper00** [comment]
Done

**Comment by recallmenot** [comment]
Nice! was thinking about adding it, but figured showing where to find it would be good enough.

**Comment by recallmenot** [comment]
but maybe rename it to "tim2_pwm_remap" so the names stay together in the examples list (coherence)

**Comment by prosper00** [comment]
done.

**Comment by recallmenot** [comment]
how did you do that without having to do a new PR?? what wizardry is this?

**Comment by prosper00** [comment]
I made the changes in my fork that I initiated the PR from, then 'git add -A; git commit; git push'

**Comment by recallmenot** [comment]
Nothing else? And here I was always doing a new PR for each modification on my fork.

**Comment by prosper00** [comment]
> Nothing else? And here I was always doing a new PR for each modification on my fork.

No, nothing else. Git seems to be on top of it, doing its magic. The git push automatically updates the PR, triggers the CI, etc.

**Pull request merged**
