### PR TITLE
add support NHC-Link042 to minichlink

### PR DESCRIPTION
**Pull request by NgoHungCuong**
- Delete .o file.
- Add STM32F042 hex file.

### CODE REVIEW

**Comment by cnlohr** [comment]
Thanks! Looks great!

**Comment by 74th** [comment]
It does not appear that the NCH-LINK hex file in the description is not included.

**Comment by NgoHungCuong** [comment]
Because .gitignore rule
-------------------------
.pio
.vscode
*.elf
*.hex
*.lst
*.bin
*.map
You can use MDK ARM to compile

**Comment by cnlohr** [comment]
You can manually add .hex files with `add -f {file}` - for the .hex, that would be nice, @NgoHungCuong

**Pull request merged**
