### PR TITLE
Minor build improvements

### PR DESCRIPTION
**Pull request by cw2**
Minor build improvements:
- #include <stdio.h> moved to ch32v003fun.h
- added build_all.cmd to build all examples

### CODE REVIEW

**Comment by cnlohr** [comment]
@cw2 I am deliberately adding `#include <stdio.h>` so that people who look at the code are consciously aware they can just `printf(...)` from the code.  Like there is no technical reason to add it, but I wanted to express it from a intellectual standpoint.

Is there a technical reason to remove it?

**Comment by cw2** [comment]
I see, good point - no need to remove `#include <stdio.h>` then (I have removed/reverted the commit).

Also, I have split `.option arch, +zicsr`, will do a separate PR associated with the respective issue.

**Comment by cnlohr** [comment]
Blehhhhhhhh I can't get this to compile on windows with `del /Q /F` 

What Make are you using?

**Comment by cw2** [comment]
I do not have any extra tools installed except what comes with the toolchain - there is make.exe in the bin directory...

**Comment by cnlohr** [comment]
I must be using a different make.  They appear to be mutually exclusive.  I spent about an hour trying to get something to autodetct if I even could execute `del` but I couldn't figure it out.  Maybe I need to do it the other way around, i.e. see if I can execute rm.

Well, don't install anything extra.  I want to figure this out.

**Pull request merged**
