### PR TITLE
Prevent minichlink from hanging with some CH32V003 revisions and WCH-LinkE

### PR DESCRIPTION
**Pull request by mverdon**
This is a fix for issue #371. Some CH32V003 revisions will get minichlink stuck in an infinite loop when writing to `DMCFGR` twice in a row.

If anyone has chips with revisions different from what is listed in the issue (i.e. `02D13` and `12E22`) and different from the SOP-8 variant with revision `D26`, please confirm that this does not break minichlink.

### CODE REVIEW

**Comment by cnlohr** [comment]
I just can't find a situation where this fails so I'll just merge.

**Comment by danielkucera** [comment]
To add more info here, the flashing also fails with official WCH-LinkUtility V2.30 with following error:
```
12:02:14:354>> The choosen WCH-Link is:[#1]
12:02:14:369>> Begin to set chip type...
12:02:14:470>> Succeed
12:02:14:470>> Begin to Program...
12:02:14:470>> Failed,please check the status of WCH-Link and the chip! Error:4
12:02:14:470>> Operation is Failed
```

Snímka

Reads work ok though.

Thank you for the great work on this project!

**Comment by xsrf** [comment]
Thx, this probably saved me so much time! I just got a complete batch of PCBs and none would work. minichlink identified the chip but wouldn't upload. This saved me. The chips I've used before without issues were `J4M6 D03` and `J4M6 E11`. The chips that now caused the issue with my old minichlink were `J4M6 E36`.
I checked, and my old chips also work fine with the new minichlink version. However, the "Part Type:" reports different values and also `minichlink` and `minichlink -i` now cause a reboot of the chip which my old version didn't, but that's a non issue and probably not even related to this pr.
I used the windows binary from this repo.

**Comment by gsteiert** [comment]
This saved me too. Thanks for fixing this.

**Pull request merged**
