### PR TITLE
Make project PlatformIO-compatible

### PR DESCRIPTION
**Pull request by maxgerhardt**
Adds a simple configuration file with which the examples can be built, uploaded and debugged. Even contains a serial montior. All within VSCode and the PlatformIO extension. Enables nicer code GUI code editing, uploading and debugging in one streamlined workflow.

Also adds Github Actions CI to test-build every project.

The [platform-ch32v](https://github.com/Community-PIO-CH32V/platform-ch32v) in turn uses reuploaded toolchains and OpenOCD from MounRiver.

grafik

### CODE REVIEW

**Comment by NgoHungCuong** [comment]
Can you help me: how to config to debug on VSC.
I dont want to use platform-IO.

**Comment by cnlohr** [comment]
What is the actual output from CI with this?   I really like it and would def consider accepting it!

**Comment by NgoHungCuong** [comment]
How about https://github.com/cnlohr/ch32v003fun/pull/10 @cnlohr

**Comment by maxgerhardt** [comment]
@cnlohr 
>What is the actual output from CI with this? 

See https://github.com/Community-PIO-CH32V/ch32v003fun/actions/runs/4335875547

>Can you help me: how to config to debug on VSC.

See https://github.com/openwch/ch32v003/blob/main/EVT/PUB/CH32V00x%20Evaluation%20Board%20Reference-EN.pdf. Basically I
1. Have a WCH-Link**E** 
2. From debugger to target board, connect GND -> GND, 3.3V -> VCC, SWDIO -> PD1
3. Use MounRiver's OpenOCD version (e.g. for Windows reuploaded at https://github.com/Community-PIO-CH32V/tool-openocd-riscv-wch)
4. Use `bin\openocd.exe -s bin -f wch-riscv.cfg`
5. It should connect to the chip and start a GDB server
```
>bin\openocd.exe -s bin -f wch-riscv.cfg
Open On-Chip Debugger 0.11.0+dev-02415-gfad123a16-dirty (2023-01-03-10:00)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'sdi'
Warn : Transport "sdi" was already selected
Ready for Remote Connections
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : WCH-LinkE  mode:RV version 2.8
Info : wlink_init ok
Info : clock speed 6000 kHz
Info : [wch_riscv.cpu.0] datacount=2 progbufsize=8
Info : [wch_riscv.cpu.0] Examined RISC-V core; found 1 harts
Info : [wch_riscv.cpu.0]  XLEN=32, misa=0x40800014
[wch_riscv.cpu.0] Target successfully examined.
Info : starting gdb server for wch_riscv.cpu.0 on 3333
Info : Listening on port 3333 for gdb connections
```
7. Use your RISC-V's toolchain's GDB to connect to it (give it the elf file as argument then `target remote :3333` to connect)

If you wanna integrate this in VSCode, just use the "cortex-debug" extension, but downgrade the version to 1.6.0 (since that one doesn't require gdb version >= 9 which the MonuRiver toolchain version is not, it's 8), then create a `.vscode/launch.json`
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceRoot}",
            "executable": ".pio/build/fulldemo/firmware.elf",
            "name": "Debug with OpenOCD",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "configFiles": ["wch-riscv.cfg"],
            "searchDir": ["C:/Users/Max/.platformio/packages/tool-openocd-riscv-wch/bin/"],
            "runToEntryPoint": "main",
            "showDevDebugOutput": "none",
            "gdbPath": "C:/Users/Max/.platformio/packages/toolchain-riscv/bin/riscv-none-embed-gdb.exe",
            "preLaunchCommands": [
                "set mem inaccessible-by-default off",
                "set arch riscv:rv32",
                "set remotetimeout unlimited",
            ],
            "svdFile": "C:/Users/Max/.platformio/platforms/ch32v/misc/svd/CH32V003xx.svd"
        }
    ]
}
```
(of course adapt the paths) and a `.vscode/settings.json` with
```
{
    "cortex-debug.openocdPath": "C:/Users/Max/.platformio/packages/tool-openocd-riscv-wch/bin/openocd.exe"
}
```
where you set your OpenOCD path. The firmware should be compiled with debug info (`-Og -g3 -ggdb3`) to enable better debugging. Then you can debug nicely in VSCode..

grafik

**Comment by NgoHungCuong** [comment]
Thank you. But it take a lot of time when start platform-IO. That cause I want to manual config.

**Comment by maxgerhardt** [comment]
I've also added the CI job to build via your native Makefile build system now, in parallel to PlatformIO, see https://github.com/Community-PIO-CH32V/ch32v003fun/actions/runs/4336080506.

**Comment by cnlohr** [comment]
@maxgerhardt I decided to try to hit this up early.  I switched things around.  I still have the EVT (lite) if people want it.  But I finally added it so I have a single .c and .h to do the build.  

I've currently converted over `blink` to use it.

Additionally, I added instructions for pure windows builds so the only requirement is the RISC-V compiler, which I have a link to a prebuilt one in the main readme.

How do you feel about these changes?  Up for integrating it?

**Comment by maxgerhardt** [comment]
Makefile build was completely unaffected, PlatformIO build was corrected, see [new run](https://github.com/Community-PIO-CH32V/ch32v003fun/actions).

**Comment by maxgerhardt** [comment]
Time traveller?
image

**Comment by cnlohr** [comment]
Looks good!

**Comment by cnlohr** [comment]
Oh crud... there's a conflict.

**Comment by cnlohr** [comment]
Thanks!

**Comment by maxgerhardt** [comment]
NOO don't merge yet the CI doesn't go through. I'll have to do another PR now. Some projects were definitely not going through the last time I checked

**Comment by cnlohr** [comment]
oh crud!  sorry

**Comment by maxgerhardt** [comment]
Yeah I'll have to check on this project's error 

grafik

**Comment by cnlohr** [comment]
@maxgerhardt fixed.

**Comment by cnlohr** [comment]
I forgot and added a feature that would break if you aren't compiling for the debug interface.

**Comment by maxgerhardt** [comment]
And what's the type of error that CI will catch from now on. CI now goes through!

But still, the makefile and PlatformIO workflow doesn't yet build all projects since new ones were added. I'll come up with a smart way of getting all example folders instead of hardcoding them, maybe [like this](https://github.com/CommunityGD32Cores/gd32-pio-projects/blob/main/.github/workflows/examples.yml#L6-L13)

**Comment by cnlohr** [comment]
Are you up for chatting in the #ch32v003 channel in my discord? https://discord.gg/CCeyWyZ

**Pull request merged**
