### PR TITLE
Update standby examples and add implementation notes.

### PR DESCRIPTION
**Pull request by baoshi**
Set GPIOs to input pull-up/pull-down is required to achieve 10uA standby current. Update examples and added notes.

### CODE REVIEW

**Comment by cnlohr** [comment]
Really like some of these changes, especially the documentation ones, but, using large streams of binary digits is a recipe to confuse people, please use more of the defines from ch32v003fun.

**Comment by marekmaskarinec** [comment]
Maybe this level of documentation could be the standard for all examples.

**Comment by baoshi** [comment]
Have relooked into the standby current and found my previous result not entirely correct. Have updated GPIO configuration notes and examples accordingly.

**Comment by cnlohr** [comment]
Looks pretty good now.

**Pull request merged**
