### PR TITLE
Add an Arduino-based SWIO programmer

### PR DESCRIPTION
**Pull request by BlueSyncLine**
I implemented a quick and dirty SWIO interface based on an Arduino Uno R3 board.
For the specific boards that I have, target reset logic seems to be required, so it was added as well.

Regards,
- Mark

### CODE REVIEW

**Comment by cnlohr** [comment]
I am very interested in adding support for the most programmers possible into minichlink, however, I am hoping to link them to the actual programmer project elsewhere instead of including the programmers here. I, early on, allowed for the NCHlink042, but I would rather avoid that moving forward, since fixes would have to go through me and I'm just not an expert.

Is it OK if the firmware lives in a separate repository and link it from your driver for minichlink?

**Comment by BlueSyncLine** [comment]
Certainly, I already have it in a separate repo:
https://gitlab.com/BlueSyncLine/arduino-ch32v003-swio.

You can exclude commit 0c404e2 which pertains solely to the actual
implementation and not the driver.

Regards,
- Mark

**Comment by cnlohr** [comment]
> You can exclude commit [0c404e2](https://github.com/cnlohr/ch32v003fun/commit/0c404e23d862f83c3daf4ae7dc8c64a7822886e7) which pertains solely to the actual

You will need to exclude it, to use the online workflow.

Also, it not supporting Windows is a pretty black eye, that would be good.

**Comment by maxgerhardt** [comment]
I'd love to see the serial code being generalized and usable for Windows too. I've worked a tiny bit on [seriallib.cpp](https://github.com/imabot2/serialib/blob/master/lib/serialib.cpp) in the past, that's basically a template on how to compile-time switch in Windows or Unix serial functions. If I remember right, `avrdude` also has a tiny serial abstraction layer written in C.

Another idea would be to generalize the firmware running on the Arduino Uno to use the general Arduino framework (and even there you can do fast port manipulation in Arduino-like way, see [here](https://github.com/arduino/ArduinoCore-avr/blob/eabd762a1edcf076877b7bec28b7f99099141473/cores/arduino/Arduino.h#L178-L184)). That way people could use many more boards as their programmer.

**Comment by cnlohr** [comment]
Any chance you would update this to remove the arduino code? And add clarifications on how to build/test?  Others can then more easily test and may add Windows support.

**Comment by BlueSyncLine** [comment]
@cnlohr  I removed the unnecessary commit. What clarifications on building would be desired?

**Comment by AlexanderMandera** [comment]
Currently, it does not compile on Windows:

```bash
ardulink.c:5:10: fatal error: termios.h: No such file or directory
    5 | #include <termios.h>
      |          ^~~~~~~~~~~
```

You may check if the `WINDOWS` macro is defined and prevent ardulink from being included until there is proper Windows support implemented.

**Comment by BlueSyncLine** [comment]
Hello,
I just spotted an issue.

The changes I committed might break the other programmers, as
MCF.TargetReset is NULL for everything except for the Ardulink...
https://github.com/cnlohr/ch32v003fun/blob/03f8a99101bcfbc23df753e3880db678958c2599/minichlink/minichlink.c#L1669

**Comment by cnlohr** [comment]
already fixe dit.

**Comment by BlueSyncLine** [comment]
Just saw it, apologies.
Thank you!

**Pull request merged**
